wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/trainer/train.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 16
data:
  desc: null
  value: COCO
decay:
  desc: null
  value: Adam Standard
epochs:
  desc: null
  value: 5
img_resolution:
  desc: null
  value: 256
keypoint_radius:
  desc: null
  value: 5
loss:
  desc: null
  value: bce_logisticloss
lr:
  desc: null
  value: Adam Standard
metrics:
  desc: null
  value:
  - <tensorflow.python.keras.metrics.Precision object at 0x7f2cffdc3ed0>
  - <tensorflow.python.keras.metrics.Recall object at 0x7f2c7dd938d0>
  - <tensorflow.python.keras.metrics.AUC object at 0x7f2c7dd93c90>
model:
  desc: null
  value: UNet
optimizer:
  desc: null
  value: <tensorflow.python.keras.optimizer_v2.adam.Adam object at 0x7f2c7c145310>
samples:
  desc: null
  value: 4250
use_generator:
  desc: null
  value: true
val_samples:
  desc: null
  value: 750
